name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      VERCEL_ORG_ID: olegs-projects-bfc4e11a
      VERCEL_PROJECT_ID: prj_6HewqIVhYFQFgim5yQPJjvz6ucHa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        working-directory: frontend
        run: vercel --yes --token=${{ secrets.VERCEL_TOKEN }}
